/* A context-free grammar for formulas.
 *
 * Go to https://www.bottlecaps.de/rr/ui to view a syntax diagram of the grammar.
 */

Formula     ::= '=' Expr | Text
Expr        ::= Number
              | Cell
              | Range
              | Application
Cell        ::= Coord
Range       ::= Coord ':' Coord
Application ::= Identifier '(' (Expr (',' Expr)*)? ')'

/* Lexemes */

Text       ::= [^=] .*
Number     ::= '-'? [0-9]+ ('.' [0-9]*)?
Coord      ::= [A-Z] [1-9]? [0-9]
Identifier ::= [a-zA-Z_] [a-zA-Z0-9_]*
